import type { Metadata } from 'next';
import { Montserrat, Bebas_Neue } from 'next/font/google';
import { Providers } from '@/providers/Providers';
import Navbar from '@/components/Navbar/Navbar';
import './globals.css';
import { locales } from '@/locales';
import { unstable_setRequestLocale } from 'next-intl/server';

const bebasNeue = Bebas_Neue({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-bebas-neue',
});
const montserrat = Montserrat({
  weight: ['400', '700'], // Specify the weights you need
  subsets: ['latin'], // Specify the subsets you need
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale} style={{ scrollBehavior: 'smooth' }}>
      <body
        className={`${montserrat.variable} ${bebasNeue.variable} from-light-black flex flex-col items-center justify-center bg-gradient-to-b to-black`}
      >
        <Providers>
          <Navbar />
          <main className={`h-full w-full max-w-screen-xl px-4 md:px-6`}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
