import type { Metadata } from 'next';
import { Montserrat, Onest } from 'next/font/google';
import { Providers } from '@/providers/Providers';
import Navbar from '@/components/Navbar/Navbar';
import './globals.css';
import { locales } from '@/locales';
import { unstable_setRequestLocale } from 'next-intl/server';
import Footer from '@/components/Footer/Footer';

const montserrat = Montserrat({
  weight: ['400', '700'], // Specify the weights you need
  subsets: ['latin'], // Specify the subsets you need
  variable: '--font-montserrat',
});

const onest = Onest({
  weight: ['400', '700'], // Specify the weights you need
  subsets: ['latin'], // Specify the subsets you need
  variable: '--font-onest', // Optional: Define a custom CSS variable
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale} style={{ scrollBehavior: 'smooth' }}>
      <body
        className={`${montserrat.variable} ${onest.variable} relative flex h-full w-full flex-col items-center justify-center scroll-smooth bg-black font-onest`}
      >
        <Providers>
          <Navbar />
          <div className="fixed left-0 top-0 -z-10 h-full w-full">
            <div className="absolute bottom-0 left-0 right-0 top-0 -z-10 bg-[linear-gradient(to_right,_#4f4f4f2e_1px,_transparent_1px),_linear-gradient(to_bottom,_#8080800a_1px,_transparent_1px)] bg-[length:14px_24px]"></div>

            <div className="absolute left-0 right-0 top-[-10%] -z-10 h-[1000px] w-[1000px] rounded-full bg-[radial-gradient(circle_400px_at_50%_50%,_#fbfbfb36,_#030303)]"></div>
          </div>
          <main className={`flex h-full w-full justify-center pb-16`}>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
